### ISSUE TITLE
Adding Highlight for Math solution

### ISSUE THREAD

**Issue by kreativmonkey** [kreativmonkey/pandoc-wbh-template#20]
Es sieht eigentlich immer ganz nett aus bei einer langen Rechnung das Ergebniss und Zwischenergebnis zu unterstreichen. Hierfür könnten wir noch ein Kommando erzeugen welches man mit diesem Template nutzen kann.

**Comment by aslmx** [comment]
Ansich keine schlechte Idee, aber was spricht dagegeben, das mit `\bold{x}` für den Einzelfall zu machen, wo man doch eh schon LaTeX schreibt? :thinking:

**Comment by kreativmonkey** [comment]
Ich dachte da eher an \solution{x} und dabei wäre dann x doppelt unterstrichen.
