### ISSUE TITLE
Include task sheet PDF

### ISSUE THREAD

**Issue by kreativmonkey** [kreativmonkey/pandoc-wbh-template#21]
Um ein PDF mit angehängtem oder vorangestellten (müsste man klären) Aufgabenblatt zu erhalten wäre es cool eine Variable zu integrieren die das ermöglicht. Wie das geht steht hier: https://stackoverflow.com/a/2739710

Variable könnte alse sowas wie "task-sheet" oder "include-tasks" heißen.

**Comment by aslmx** [comment]
#22 implements this.
