### ISSUE TITLE
oben und unten je 2 cm

### ISSUE THREAD

**Issue by kreativmonkey** [kreativmonkey/pandoc-wbh-template#28]

**Comment by kreativmonkey** [comment]
Der obere und untere Abstand ist derzeit etwas anders Definiert...

Oben: 2,7cm und unten 3,5cm. Ob das ein Problem ist sollte man evtl. noch klären.

**Comment by aslmx** [comment]
Könnte man doch über Variablen regeln, die sonst auf 27mm bzw. 35mm zurückfallen wenn sie nicht gesetzt sind?

**Comment by kreativmonkey** [comment]
Die Frage ist, wie strickt ist der Leitfaden zu befolgen? Variablen an sich sind natürlich hilfreich, müssen jedoch nicht bedingt sein.

**Comment by aslmx** [comment]
Egal wie strikt der Leitfaden zu befolgen ist (für B-Aufgaben die wir ja auch unterstützen gibt es ja afaik keine wirkliche einzuhaltende Form), man kann die Ränder mit dem PR ja jetzt einfach anpassen...

**Comment by kreativmonkey** [comment]
Um die Optik nicht zu zerstören sind 2.5cm oben und unten das minimum. Ich denke das ist ein guter Kompromiss um den Leitfaden zu entsprechen.

**Comment by kreativmonkey** [comment]
63d94a6a90619360b63a6936658e16a26d5e5e24 closed
