### ISSUE TITLE
Tabellen-, Abkürzungs- und Abbildungsverzeichnis hinter dem Textteil

### ISSUE THREAD

**Issue by kreativmonkey** [kreativmonkey/pandoc-wbh-template#29]
Aktuell werden alle Verzeichnisse vor dem Text angelegt. Es müsste geklärt werden ob diese Hinter die Quellenangaben (ich vermute ja) kommen oder davor. Dann sollten sie diesbezüglich umgelegt werden.

**Comment by aslmx** [comment]
Kann man vielleicht konfigurierbar gestalten (so wie bei meinem includepdf PR)

**Comment by kreativmonkey** [comment]
https://ftp.agdsn.de/pub/mirrors/latex/dante/macros/latex/contrib/glossaries/glossariesbegin.pdf <- Abkürzungsverzeichnis mit glossaries
